blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/mohamedhabibwork/abp-gen/discussions
    about: Ask questions or start a discussion
  - name: Security Issue
    url: https://github.com/mohamedhabibwork/abp-gen/security/advisories/new
    about: Report a security vulnerability

